'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type IToolboxField, type LSApiElement, type LSApiRole, type LSApiRoleType, type LSApiTemplate, type LSMutateEvent, type LsDocumentOptionsCustomEvent, type LsDocumentViewerCustomEvent, type LsEditorFieldCustomEvent, type LsFieldAlignmentCustomEvent, type LsFieldContentCustomEvent, type LsFieldDimensionsCustomEvent, type LsFieldDistributeCustomEvent, type LsFieldFooterCustomEvent, type LsFieldFormatCustomEvent, type LsFieldPlacementCustomEvent, type LsFieldPropertiesAdvancedCustomEvent, type LsFieldPropertiesMultipleCustomEvent, type LsFieldSizeCustomEvent, type LsParticipantCardCustomEvent, type LsParticipantManagerCustomEvent, type LsParticipantSelectCustomEvent, type LsRecipientCardCustomEvent, type LsTitleInputCustomEvent, type LsToolbarCustomEvent } from "legalesign-document-viewer";
import { LsAddNewButton as LsAddNewButtonElement, defineCustomElement as defineLsAddNewButton } from "legalesign-document-viewer/dist/components/ls-add-new-button.js";
import { LsBadge as LsBadgeElement, defineCustomElement as defineLsBadge } from "legalesign-document-viewer/dist/components/ls-badge.js";
import { LsBanner as LsBannerElement, defineCustomElement as defineLsBanner } from "legalesign-document-viewer/dist/components/ls-banner.js";
import { LsButton as LsButtonElement, defineCustomElement as defineLsButton } from "legalesign-document-viewer/dist/components/ls-button.js";
import { LsCard as LsCardElement, defineCustomElement as defineLsCard } from "legalesign-document-viewer/dist/components/ls-card.js";
import { LsCheckboxInput as LsCheckboxInputElement, defineCustomElement as defineLsCheckboxInput } from "legalesign-document-viewer/dist/components/ls-checkbox-input.js";
import { LsComposeLoader as LsComposeLoaderElement, defineCustomElement as defineLsComposeLoader } from "legalesign-document-viewer/dist/components/ls-compose-loader.js";
import { LsComposeManager as LsComposeManagerElement, defineCustomElement as defineLsComposeManager } from "legalesign-document-viewer/dist/components/ls-compose-manager.js";
import { LsDetailsSection as LsDetailsSectionElement, defineCustomElement as defineLsDetailsSection } from "legalesign-document-viewer/dist/components/ls-details-section.js";
import { LsDocumentOptions as LsDocumentOptionsElement, defineCustomElement as defineLsDocumentOptions } from "legalesign-document-viewer/dist/components/ls-document-options.js";
import { LsDocumentViewer as LsDocumentViewerElement, defineCustomElement as defineLsDocumentViewer } from "legalesign-document-viewer/dist/components/ls-document-viewer.js";
import { LsDropdownItem as LsDropdownItemElement, defineCustomElement as defineLsDropdownItem } from "legalesign-document-viewer/dist/components/ls-dropdown-item.js";
import { LsDropdown as LsDropdownElement, defineCustomElement as defineLsDropdown } from "legalesign-document-viewer/dist/components/ls-dropdown.js";
import { LsEditorField as LsEditorFieldElement, defineCustomElement as defineLsEditorField } from "legalesign-document-viewer/dist/components/ls-editor-field.js";
import { LsEditorTable as LsEditorTableElement, defineCustomElement as defineLsEditorTable } from "legalesign-document-viewer/dist/components/ls-editor-table.js";
import { LsFeatureColumn as LsFeatureColumnElement, defineCustomElement as defineLsFeatureColumn } from "legalesign-document-viewer/dist/components/ls-feature-column.js";
import { LsFieldAlignment as LsFieldAlignmentElement, defineCustomElement as defineLsFieldAlignment } from "legalesign-document-viewer/dist/components/ls-field-alignment.js";
import { LsFieldContent as LsFieldContentElement, defineCustomElement as defineLsFieldContent } from "legalesign-document-viewer/dist/components/ls-field-content.js";
import { LsFieldDimensions as LsFieldDimensionsElement, defineCustomElement as defineLsFieldDimensions } from "legalesign-document-viewer/dist/components/ls-field-dimensions.js";
import { LsFieldDistribute as LsFieldDistributeElement, defineCustomElement as defineLsFieldDistribute } from "legalesign-document-viewer/dist/components/ls-field-distribute.js";
import { LsFieldFooter as LsFieldFooterElement, defineCustomElement as defineLsFieldFooter } from "legalesign-document-viewer/dist/components/ls-field-footer.js";
import { LsFieldFormat as LsFieldFormatElement, defineCustomElement as defineLsFieldFormat } from "legalesign-document-viewer/dist/components/ls-field-format.js";
import { LsFieldPlacement as LsFieldPlacementElement, defineCustomElement as defineLsFieldPlacement } from "legalesign-document-viewer/dist/components/ls-field-placement.js";
import { LsFieldPropertiesAdvanced as LsFieldPropertiesAdvancedElement, defineCustomElement as defineLsFieldPropertiesAdvanced } from "legalesign-document-viewer/dist/components/ls-field-properties-advanced.js";
import { LsFieldPropertiesAutosign as LsFieldPropertiesAutosignElement, defineCustomElement as defineLsFieldPropertiesAutosign } from "legalesign-document-viewer/dist/components/ls-field-properties-autosign.js";
import { LsFieldPropertiesContainer as LsFieldPropertiesContainerElement, defineCustomElement as defineLsFieldPropertiesContainer } from "legalesign-document-viewer/dist/components/ls-field-properties-container.js";
import { LsFieldPropertiesDate as LsFieldPropertiesDateElement, defineCustomElement as defineLsFieldPropertiesDate } from "legalesign-document-viewer/dist/components/ls-field-properties-date.js";
import { LsFieldPropertiesDropdown as LsFieldPropertiesDropdownElement, defineCustomElement as defineLsFieldPropertiesDropdown } from "legalesign-document-viewer/dist/components/ls-field-properties-dropdown.js";
import { LsFieldPropertiesEmail as LsFieldPropertiesEmailElement, defineCustomElement as defineLsFieldPropertiesEmail } from "legalesign-document-viewer/dist/components/ls-field-properties-email.js";
import { LsFieldPropertiesFile as LsFieldPropertiesFileElement, defineCustomElement as defineLsFieldPropertiesFile } from "legalesign-document-viewer/dist/components/ls-field-properties-file.js";
import { LsFieldPropertiesGeneral as LsFieldPropertiesGeneralElement, defineCustomElement as defineLsFieldPropertiesGeneral } from "legalesign-document-viewer/dist/components/ls-field-properties-general.js";
import { LsFieldPropertiesImage as LsFieldPropertiesImageElement, defineCustomElement as defineLsFieldPropertiesImage } from "legalesign-document-viewer/dist/components/ls-field-properties-image.js";
import { LsFieldPropertiesMultiple as LsFieldPropertiesMultipleElement, defineCustomElement as defineLsFieldPropertiesMultiple } from "legalesign-document-viewer/dist/components/ls-field-properties-multiple.js";
import { LsFieldPropertiesNumber as LsFieldPropertiesNumberElement, defineCustomElement as defineLsFieldPropertiesNumber } from "legalesign-document-viewer/dist/components/ls-field-properties-number.js";
import { LsFieldPropertiesSignature as LsFieldPropertiesSignatureElement, defineCustomElement as defineLsFieldPropertiesSignature } from "legalesign-document-viewer/dist/components/ls-field-properties-signature.js";
import { LsFieldPropertiesText as LsFieldPropertiesTextElement, defineCustomElement as defineLsFieldPropertiesText } from "legalesign-document-viewer/dist/components/ls-field-properties-text.js";
import { LsFieldProperties as LsFieldPropertiesElement, defineCustomElement as defineLsFieldProperties } from "legalesign-document-viewer/dist/components/ls-field-properties.js";
import { LsFieldSize as LsFieldSizeElement, defineCustomElement as defineLsFieldSize } from "legalesign-document-viewer/dist/components/ls-field-size.js";
import { LsFieldTypeDisplay as LsFieldTypeDisplayElement, defineCustomElement as defineLsFieldTypeDisplay } from "legalesign-document-viewer/dist/components/ls-field-type-display.js";
import { LsFormfield as LsFormfieldElement, defineCustomElement as defineLsFormfield } from "legalesign-document-viewer/dist/components/ls-formfield.js";
import { LsHeaderBar as LsHeaderBarElement, defineCustomElement as defineLsHeaderBar } from "legalesign-document-viewer/dist/components/ls-header-bar.js";
import { LsHelperBar as LsHelperBarElement, defineCustomElement as defineLsHelperBar } from "legalesign-document-viewer/dist/components/ls-helper-bar.js";
import { LsIconButton as LsIconButtonElement, defineCustomElement as defineLsIconButton } from "legalesign-document-viewer/dist/components/ls-icon-button.js";
import { LsIconCheckButton as LsIconCheckButtonElement, defineCustomElement as defineLsIconCheckButton } from "legalesign-document-viewer/dist/components/ls-icon-check-button.js";
import { LsIcon as LsIconElement, defineCustomElement as defineLsIcon } from "legalesign-document-viewer/dist/components/ls-icon.js";
import { LsInputWrapper as LsInputWrapperElement, defineCustomElement as defineLsInputWrapper } from "legalesign-document-viewer/dist/components/ls-input-wrapper.js";
import { LsKeyboardShortcuts as LsKeyboardShortcutsElement, defineCustomElement as defineLsKeyboardShortcuts } from "legalesign-document-viewer/dist/components/ls-keyboard-shortcuts.js";
import { LsLabel as LsLabelElement, defineCustomElement as defineLsLabel } from "legalesign-document-viewer/dist/components/ls-label.js";
import { LsLeftBar as LsLeftBarElement, defineCustomElement as defineLsLeftBar } from "legalesign-document-viewer/dist/components/ls-left-bar.js";
import { LsListCardButton as LsListCardButtonElement, defineCustomElement as defineLsListCardButton } from "legalesign-document-viewer/dist/components/ls-list-card-button.js";
import { LsLoadingIcon as LsLoadingIconElement, defineCustomElement as defineLsLoadingIcon } from "legalesign-document-viewer/dist/components/ls-loading-icon.js";
import { LsLoadingLogo as LsLoadingLogoElement, defineCustomElement as defineLsLoadingLogo } from "legalesign-document-viewer/dist/components/ls-loading-logo.js";
import { LsLoading as LsLoadingElement, defineCustomElement as defineLsLoading } from "legalesign-document-viewer/dist/components/ls-loading.js";
import { LsNavbar as LsNavbarElement, defineCustomElement as defineLsNavbar } from "legalesign-document-viewer/dist/components/ls-navbar.js";
import { LsNotification as LsNotificationElement, defineCustomElement as defineLsNotification } from "legalesign-document-viewer/dist/components/ls-notification.js";
import { LsNumberInput as LsNumberInputElement, defineCustomElement as defineLsNumberInput } from "legalesign-document-viewer/dist/components/ls-number-input.js";
import { LsParticipantCard as LsParticipantCardElement, defineCustomElement as defineLsParticipantCard } from "legalesign-document-viewer/dist/components/ls-participant-card.js";
import { LsParticipantManager as LsParticipantManagerElement, defineCustomElement as defineLsParticipantManager } from "legalesign-document-viewer/dist/components/ls-participant-manager.js";
import { LsParticipantSelect as LsParticipantSelectElement, defineCustomElement as defineLsParticipantSelect } from "legalesign-document-viewer/dist/components/ls-participant-select.js";
import { LsPropsSection as LsPropsSectionElement, defineCustomElement as defineLsPropsSection } from "legalesign-document-viewer/dist/components/ls-props-section.js";
import { LsRadioGroup as LsRadioGroupElement, defineCustomElement as defineLsRadioGroup } from "legalesign-document-viewer/dist/components/ls-radio-group.js";
import { LsRadioInput as LsRadioInputElement, defineCustomElement as defineLsRadioInput } from "legalesign-document-viewer/dist/components/ls-radio-input.js";
import { LsRecipientCard as LsRecipientCardElement, defineCustomElement as defineLsRecipientCard } from "legalesign-document-viewer/dist/components/ls-recipient-card.js";
import { LsRecipientManager as LsRecipientManagerElement, defineCustomElement as defineLsRecipientManager } from "legalesign-document-viewer/dist/components/ls-recipient-manager.js";
import { LsSelectInput as LsSelectInputElement, defineCustomElement as defineLsSelectInput } from "legalesign-document-viewer/dist/components/ls-select-input.js";
import { LsStatusbar as LsStatusbarElement, defineCustomElement as defineLsStatusbar } from "legalesign-document-viewer/dist/components/ls-statusbar.js";
import { LsTabs as LsTabsElement, defineCustomElement as defineLsTabs } from "legalesign-document-viewer/dist/components/ls-tabs.js";
import { LsTag as LsTagElement, defineCustomElement as defineLsTag } from "legalesign-document-viewer/dist/components/ls-tag.js";
import { LsTextInput as LsTextInputElement, defineCustomElement as defineLsTextInput } from "legalesign-document-viewer/dist/components/ls-text-input.js";
import { LsText as LsTextElement, defineCustomElement as defineLsText } from "legalesign-document-viewer/dist/components/ls-text.js";
import { LsTextareaInput as LsTextareaInputElement, defineCustomElement as defineLsTextareaInput } from "legalesign-document-viewer/dist/components/ls-textarea-input.js";
import { LsTimelineStep as LsTimelineStepElement, defineCustomElement as defineLsTimelineStep } from "legalesign-document-viewer/dist/components/ls-timeline-step.js";
import { LsTimeline as LsTimelineElement, defineCustomElement as defineLsTimeline } from "legalesign-document-viewer/dist/components/ls-timeline.js";
import { LsTitleInput as LsTitleInputElement, defineCustomElement as defineLsTitleInput } from "legalesign-document-viewer/dist/components/ls-title-input.js";
import { LsToggle as LsToggleElement, defineCustomElement as defineLsToggle } from "legalesign-document-viewer/dist/components/ls-toggle.js";
import { LsToolbar as LsToolbarElement, defineCustomElement as defineLsToolbar } from "legalesign-document-viewer/dist/components/ls-toolbar.js";
import { LsToolboxField as LsToolboxFieldElement, defineCustomElement as defineLsToolboxField } from "legalesign-document-viewer/dist/components/ls-toolbox-field.js";
import { LsTooltip as LsTooltipElement, defineCustomElement as defineLsTooltip } from "legalesign-document-viewer/dist/components/ls-tooltip.js";
import { LsValidationManager as LsValidationManagerElement, defineCustomElement as defineLsValidationManager } from "legalesign-document-viewer/dist/components/ls-validation-manager.js";
import { LsValidationTag as LsValidationTagElement, defineCustomElement as defineLsValidationTag } from "legalesign-document-viewer/dist/components/ls-validation-tag.js";
import { TestItem as TestItemElement, defineCustomElement as defineTestItem } from "legalesign-document-viewer/dist/components/test-item.js";
import React from 'react';

export type LsAddNewButtonEvents = NonNullable<unknown>;

export const LsAddNewButton: StencilReactComponent<LsAddNewButtonElement, LsAddNewButtonEvents> = /*@__PURE__*/ createComponent<LsAddNewButtonElement, LsAddNewButtonEvents>({
    tagName: 'ls-add-new-button',
    elementClass: LsAddNewButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsAddNewButtonEvents,
    defineCustomElement: defineLsAddNewButton
});

export type LsBadgeEvents = NonNullable<unknown>;

export const LsBadge: StencilReactComponent<LsBadgeElement, LsBadgeEvents> = /*@__PURE__*/ createComponent<LsBadgeElement, LsBadgeEvents>({
    tagName: 'ls-badge',
    elementClass: LsBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsBadgeEvents,
    defineCustomElement: defineLsBadge
});

export type LsBannerEvents = NonNullable<unknown>;

export const LsBanner: StencilReactComponent<LsBannerElement, LsBannerEvents> = /*@__PURE__*/ createComponent<LsBannerElement, LsBannerEvents>({
    tagName: 'ls-banner',
    elementClass: LsBannerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsBannerEvents,
    defineCustomElement: defineLsBanner
});

export type LsButtonEvents = NonNullable<unknown>;

export const LsButton: StencilReactComponent<LsButtonElement, LsButtonEvents> = /*@__PURE__*/ createComponent<LsButtonElement, LsButtonEvents>({
    tagName: 'ls-button',
    elementClass: LsButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsButtonEvents,
    defineCustomElement: defineLsButton
});

export type LsCardEvents = NonNullable<unknown>;

export const LsCard: StencilReactComponent<LsCardElement, LsCardEvents> = /*@__PURE__*/ createComponent<LsCardElement, LsCardEvents>({
    tagName: 'ls-card',
    elementClass: LsCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsCardEvents,
    defineCustomElement: defineLsCard
});

export type LsCheckboxInputEvents = { onHandlechange: EventName<CustomEvent<{ id: string; checked: boolean }>> };

export const LsCheckboxInput: StencilReactComponent<LsCheckboxInputElement, LsCheckboxInputEvents> = /*@__PURE__*/ createComponent<LsCheckboxInputElement, LsCheckboxInputEvents>({
    tagName: 'ls-checkbox-input',
    elementClass: LsCheckboxInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onHandlechange: 'handlechange' } as LsCheckboxInputEvents,
    defineCustomElement: defineLsCheckboxInput
});

export type LsComposeLoaderEvents = NonNullable<unknown>;

export const LsComposeLoader: StencilReactComponent<LsComposeLoaderElement, LsComposeLoaderEvents> = /*@__PURE__*/ createComponent<LsComposeLoaderElement, LsComposeLoaderEvents>({
    tagName: 'ls-compose-loader',
    elementClass: LsComposeLoaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsComposeLoaderEvents,
    defineCustomElement: defineLsComposeLoader
});

export type LsComposeManagerEvents = NonNullable<unknown>;

export const LsComposeManager: StencilReactComponent<LsComposeManagerElement, LsComposeManagerEvents> = /*@__PURE__*/ createComponent<LsComposeManagerElement, LsComposeManagerEvents>({
    tagName: 'ls-compose-manager',
    elementClass: LsComposeManagerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsComposeManagerEvents,
    defineCustomElement: defineLsComposeManager
});

export type LsDetailsSectionEvents = NonNullable<unknown>;

export const LsDetailsSection: StencilReactComponent<LsDetailsSectionElement, LsDetailsSectionEvents> = /*@__PURE__*/ createComponent<LsDetailsSectionElement, LsDetailsSectionEvents>({
    tagName: 'ls-details-section',
    elementClass: LsDetailsSectionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsDetailsSectionEvents,
    defineCustomElement: defineLsDetailsSection
});

export type LsDocumentOptionsEvents = {
    onMutate: EventName<LsDocumentOptionsCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsDocumentOptionsCustomEvent<LSMutateEvent[]>>
};

export const LsDocumentOptions: StencilReactComponent<LsDocumentOptionsElement, LsDocumentOptionsEvents> = /*@__PURE__*/ createComponent<LsDocumentOptionsElement, LsDocumentOptionsEvents>({
    tagName: 'ls-document-options',
    elementClass: LsDocumentOptionsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onUpdate: 'update'
    } as LsDocumentOptionsEvents,
    defineCustomElement: defineLsDocumentOptions
});

export type LsDocumentViewerEvents = {
    onPageRendered: EventName<CustomEvent<number>>,
    onPageChange: EventName<CustomEvent<number>>,
    onSelectFields: EventName<LsDocumentViewerCustomEvent<LSApiElement[]>>,
    onMutate: EventName<LsDocumentViewerCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsDocumentViewerCustomEvent<{ event: LSMutateEvent; template: LSApiTemplate }>>,
    onValidate: EventName<CustomEvent<{ valid: boolean }>>,
    onAddParticipant: EventName<LsDocumentViewerCustomEvent<{ name?: string | null; type: LSApiRoleType; parent?: string | null; signerIndex?: number }>>
};

export const LsDocumentViewer: StencilReactComponent<LsDocumentViewerElement, LsDocumentViewerEvents> = /*@__PURE__*/ createComponent<LsDocumentViewerElement, LsDocumentViewerEvents>({
    tagName: 'ls-document-viewer',
    elementClass: LsDocumentViewerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onPageRendered: 'pageRendered',
        onPageChange: 'pageChange',
        onSelectFields: 'selectFields',
        onMutate: 'mutate',
        onUpdate: 'update',
        onValidate: 'validate',
        onAddParticipant: 'addParticipant'
    } as LsDocumentViewerEvents,
    defineCustomElement: defineLsDocumentViewer
});

export type LsDropdownEvents = NonNullable<unknown>;

export const LsDropdown: StencilReactComponent<LsDropdownElement, LsDropdownEvents> = /*@__PURE__*/ createComponent<LsDropdownElement, LsDropdownEvents>({
    tagName: 'ls-dropdown',
    elementClass: LsDropdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsDropdownEvents,
    defineCustomElement: defineLsDropdown
});

export type LsDropdownItemEvents = NonNullable<unknown>;

export const LsDropdownItem: StencilReactComponent<LsDropdownItemElement, LsDropdownItemEvents> = /*@__PURE__*/ createComponent<LsDropdownItemElement, LsDropdownItemEvents>({
    tagName: 'ls-dropdown-item',
    elementClass: LsDropdownItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsDropdownItemEvents,
    defineCustomElement: defineLsDropdownItem
});

export type LsEditorFieldEvents = {
    onMutate: EventName<LsEditorFieldCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsEditorFieldCustomEvent<LSMutateEvent[]>>
};

export const LsEditorField: StencilReactComponent<LsEditorFieldElement, LsEditorFieldEvents> = /*@__PURE__*/ createComponent<LsEditorFieldElement, LsEditorFieldEvents>({
    tagName: 'ls-editor-field',
    elementClass: LsEditorFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onUpdate: 'update'
    } as LsEditorFieldEvents,
    defineCustomElement: defineLsEditorField
});

export type LsEditorTableEvents = NonNullable<unknown>;

export const LsEditorTable: StencilReactComponent<LsEditorTableElement, LsEditorTableEvents> = /*@__PURE__*/ createComponent<LsEditorTableElement, LsEditorTableEvents>({
    tagName: 'ls-editor-table',
    elementClass: LsEditorTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsEditorTableEvents,
    defineCustomElement: defineLsEditorTable
});

export type LsFeatureColumnEvents = { onManage: EventName<CustomEvent<'document' | 'toolbox' | 'participant' | 'recipient' | 'validation'>> };

export const LsFeatureColumn: StencilReactComponent<LsFeatureColumnElement, LsFeatureColumnEvents> = /*@__PURE__*/ createComponent<LsFeatureColumnElement, LsFeatureColumnEvents>({
    tagName: 'ls-feature-column',
    elementClass: LsFeatureColumnElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onManage: 'manage' } as LsFeatureColumnEvents,
    defineCustomElement: defineLsFeatureColumn
});

export type LsFieldAlignmentEvents = {
    onMutate: EventName<LsFieldAlignmentCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsFieldAlignmentCustomEvent<LSMutateEvent[]>>
};

export const LsFieldAlignment: StencilReactComponent<LsFieldAlignmentElement, LsFieldAlignmentEvents> = /*@__PURE__*/ createComponent<LsFieldAlignmentElement, LsFieldAlignmentEvents>({
    tagName: 'ls-field-alignment',
    elementClass: LsFieldAlignmentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onUpdate: 'update'
    } as LsFieldAlignmentEvents,
    defineCustomElement: defineLsFieldAlignment
});

export type LsFieldContentEvents = {
    onMutate: EventName<LsFieldContentCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsFieldContentCustomEvent<LSMutateEvent[]>>
};

export const LsFieldContent: StencilReactComponent<LsFieldContentElement, LsFieldContentEvents> = /*@__PURE__*/ createComponent<LsFieldContentElement, LsFieldContentEvents>({
    tagName: 'ls-field-content',
    elementClass: LsFieldContentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onUpdate: 'update'
    } as LsFieldContentEvents,
    defineCustomElement: defineLsFieldContent
});

export type LsFieldDimensionsEvents = {
    onMutate: EventName<LsFieldDimensionsCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsFieldDimensionsCustomEvent<LSMutateEvent[]>>
};

export const LsFieldDimensions: StencilReactComponent<LsFieldDimensionsElement, LsFieldDimensionsEvents> = /*@__PURE__*/ createComponent<LsFieldDimensionsElement, LsFieldDimensionsEvents>({
    tagName: 'ls-field-dimensions',
    elementClass: LsFieldDimensionsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onUpdate: 'update'
    } as LsFieldDimensionsEvents,
    defineCustomElement: defineLsFieldDimensions
});

export type LsFieldDistributeEvents = { onMutate: EventName<LsFieldDistributeCustomEvent<LSMutateEvent[]>> };

export const LsFieldDistribute: StencilReactComponent<LsFieldDistributeElement, LsFieldDistributeEvents> = /*@__PURE__*/ createComponent<LsFieldDistributeElement, LsFieldDistributeEvents>({
    tagName: 'ls-field-distribute',
    elementClass: LsFieldDistributeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMutate: 'mutate' } as LsFieldDistributeEvents,
    defineCustomElement: defineLsFieldDistribute
});

export type LsFieldFooterEvents = {
    onMutate: EventName<LsFieldFooterCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsFieldFooterCustomEvent<LSMutateEvent[]>>,
    onSelectFields: EventName<LsFieldFooterCustomEvent<LSApiElement[]>>
};

export const LsFieldFooter: StencilReactComponent<LsFieldFooterElement, LsFieldFooterEvents> = /*@__PURE__*/ createComponent<LsFieldFooterElement, LsFieldFooterEvents>({
    tagName: 'ls-field-footer',
    elementClass: LsFieldFooterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onUpdate: 'update',
        onSelectFields: 'selectFields'
    } as LsFieldFooterEvents,
    defineCustomElement: defineLsFieldFooter
});

export type LsFieldFormatEvents = { onMutate: EventName<LsFieldFormatCustomEvent<LSMutateEvent[]>> };

export const LsFieldFormat: StencilReactComponent<LsFieldFormatElement, LsFieldFormatEvents> = /*@__PURE__*/ createComponent<LsFieldFormatElement, LsFieldFormatEvents>({
    tagName: 'ls-field-format',
    elementClass: LsFieldFormatElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMutate: 'mutate' } as LsFieldFormatEvents,
    defineCustomElement: defineLsFieldFormat
});

export type LsFieldPlacementEvents = { onMutate: EventName<LsFieldPlacementCustomEvent<LSMutateEvent[]>> };

export const LsFieldPlacement: StencilReactComponent<LsFieldPlacementElement, LsFieldPlacementEvents> = /*@__PURE__*/ createComponent<LsFieldPlacementElement, LsFieldPlacementEvents>({
    tagName: 'ls-field-placement',
    elementClass: LsFieldPlacementElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMutate: 'mutate' } as LsFieldPlacementEvents,
    defineCustomElement: defineLsFieldPlacement
});

export type LsFieldPropertiesEvents = NonNullable<unknown>;

export const LsFieldProperties: StencilReactComponent<LsFieldPropertiesElement, LsFieldPropertiesEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesElement, LsFieldPropertiesEvents>({
    tagName: 'ls-field-properties',
    elementClass: LsFieldPropertiesElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesEvents,
    defineCustomElement: defineLsFieldProperties
});

export type LsFieldPropertiesAdvancedEvents = { onMutate: EventName<LsFieldPropertiesAdvancedCustomEvent<LSMutateEvent[]>> };

export const LsFieldPropertiesAdvanced: StencilReactComponent<LsFieldPropertiesAdvancedElement, LsFieldPropertiesAdvancedEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesAdvancedElement, LsFieldPropertiesAdvancedEvents>({
    tagName: 'ls-field-properties-advanced',
    elementClass: LsFieldPropertiesAdvancedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMutate: 'mutate' } as LsFieldPropertiesAdvancedEvents,
    defineCustomElement: defineLsFieldPropertiesAdvanced
});

export type LsFieldPropertiesAutosignEvents = NonNullable<unknown>;

export const LsFieldPropertiesAutosign: StencilReactComponent<LsFieldPropertiesAutosignElement, LsFieldPropertiesAutosignEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesAutosignElement, LsFieldPropertiesAutosignEvents>({
    tagName: 'ls-field-properties-autosign',
    elementClass: LsFieldPropertiesAutosignElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesAutosignEvents,
    defineCustomElement: defineLsFieldPropertiesAutosign
});

export type LsFieldPropertiesContainerEvents = NonNullable<unknown>;

export const LsFieldPropertiesContainer: StencilReactComponent<LsFieldPropertiesContainerElement, LsFieldPropertiesContainerEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesContainerElement, LsFieldPropertiesContainerEvents>({
    tagName: 'ls-field-properties-container',
    elementClass: LsFieldPropertiesContainerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesContainerEvents,
    defineCustomElement: defineLsFieldPropertiesContainer
});

export type LsFieldPropertiesDateEvents = NonNullable<unknown>;

export const LsFieldPropertiesDate: StencilReactComponent<LsFieldPropertiesDateElement, LsFieldPropertiesDateEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesDateElement, LsFieldPropertiesDateEvents>({
    tagName: 'ls-field-properties-date',
    elementClass: LsFieldPropertiesDateElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesDateEvents,
    defineCustomElement: defineLsFieldPropertiesDate
});

export type LsFieldPropertiesDropdownEvents = NonNullable<unknown>;

export const LsFieldPropertiesDropdown: StencilReactComponent<LsFieldPropertiesDropdownElement, LsFieldPropertiesDropdownEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesDropdownElement, LsFieldPropertiesDropdownEvents>({
    tagName: 'ls-field-properties-dropdown',
    elementClass: LsFieldPropertiesDropdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesDropdownEvents,
    defineCustomElement: defineLsFieldPropertiesDropdown
});

export type LsFieldPropertiesEmailEvents = NonNullable<unknown>;

export const LsFieldPropertiesEmail: StencilReactComponent<LsFieldPropertiesEmailElement, LsFieldPropertiesEmailEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesEmailElement, LsFieldPropertiesEmailEvents>({
    tagName: 'ls-field-properties-email',
    elementClass: LsFieldPropertiesEmailElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesEmailEvents,
    defineCustomElement: defineLsFieldPropertiesEmail
});

export type LsFieldPropertiesFileEvents = NonNullable<unknown>;

export const LsFieldPropertiesFile: StencilReactComponent<LsFieldPropertiesFileElement, LsFieldPropertiesFileEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesFileElement, LsFieldPropertiesFileEvents>({
    tagName: 'ls-field-properties-file',
    elementClass: LsFieldPropertiesFileElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesFileEvents,
    defineCustomElement: defineLsFieldPropertiesFile
});

export type LsFieldPropertiesGeneralEvents = NonNullable<unknown>;

export const LsFieldPropertiesGeneral: StencilReactComponent<LsFieldPropertiesGeneralElement, LsFieldPropertiesGeneralEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesGeneralElement, LsFieldPropertiesGeneralEvents>({
    tagName: 'ls-field-properties-general',
    elementClass: LsFieldPropertiesGeneralElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesGeneralEvents,
    defineCustomElement: defineLsFieldPropertiesGeneral
});

export type LsFieldPropertiesImageEvents = NonNullable<unknown>;

export const LsFieldPropertiesImage: StencilReactComponent<LsFieldPropertiesImageElement, LsFieldPropertiesImageEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesImageElement, LsFieldPropertiesImageEvents>({
    tagName: 'ls-field-properties-image',
    elementClass: LsFieldPropertiesImageElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesImageEvents,
    defineCustomElement: defineLsFieldPropertiesImage
});

export type LsFieldPropertiesMultipleEvents = {
    onMutate: EventName<LsFieldPropertiesMultipleCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsFieldPropertiesMultipleCustomEvent<LSMutateEvent[]>>
};

export const LsFieldPropertiesMultiple: StencilReactComponent<LsFieldPropertiesMultipleElement, LsFieldPropertiesMultipleEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesMultipleElement, LsFieldPropertiesMultipleEvents>({
    tagName: 'ls-field-properties-multiple',
    elementClass: LsFieldPropertiesMultipleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onUpdate: 'update'
    } as LsFieldPropertiesMultipleEvents,
    defineCustomElement: defineLsFieldPropertiesMultiple
});

export type LsFieldPropertiesNumberEvents = NonNullable<unknown>;

export const LsFieldPropertiesNumber: StencilReactComponent<LsFieldPropertiesNumberElement, LsFieldPropertiesNumberEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesNumberElement, LsFieldPropertiesNumberEvents>({
    tagName: 'ls-field-properties-number',
    elementClass: LsFieldPropertiesNumberElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesNumberEvents,
    defineCustomElement: defineLsFieldPropertiesNumber
});

export type LsFieldPropertiesSignatureEvents = NonNullable<unknown>;

export const LsFieldPropertiesSignature: StencilReactComponent<LsFieldPropertiesSignatureElement, LsFieldPropertiesSignatureEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesSignatureElement, LsFieldPropertiesSignatureEvents>({
    tagName: 'ls-field-properties-signature',
    elementClass: LsFieldPropertiesSignatureElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesSignatureEvents,
    defineCustomElement: defineLsFieldPropertiesSignature
});

export type LsFieldPropertiesTextEvents = NonNullable<unknown>;

export const LsFieldPropertiesText: StencilReactComponent<LsFieldPropertiesTextElement, LsFieldPropertiesTextEvents> = /*@__PURE__*/ createComponent<LsFieldPropertiesTextElement, LsFieldPropertiesTextEvents>({
    tagName: 'ls-field-properties-text',
    elementClass: LsFieldPropertiesTextElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldPropertiesTextEvents,
    defineCustomElement: defineLsFieldPropertiesText
});

export type LsFieldSizeEvents = { onMutate: EventName<LsFieldSizeCustomEvent<LSMutateEvent[]>> };

export const LsFieldSize: StencilReactComponent<LsFieldSizeElement, LsFieldSizeEvents> = /*@__PURE__*/ createComponent<LsFieldSizeElement, LsFieldSizeEvents>({
    tagName: 'ls-field-size',
    elementClass: LsFieldSizeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMutate: 'mutate' } as LsFieldSizeEvents,
    defineCustomElement: defineLsFieldSize
});

export type LsFieldTypeDisplayEvents = NonNullable<unknown>;

export const LsFieldTypeDisplay: StencilReactComponent<LsFieldTypeDisplayElement, LsFieldTypeDisplayEvents> = /*@__PURE__*/ createComponent<LsFieldTypeDisplayElement, LsFieldTypeDisplayEvents>({
    tagName: 'ls-field-type-display',
    elementClass: LsFieldTypeDisplayElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsFieldTypeDisplayEvents,
    defineCustomElement: defineLsFieldTypeDisplay
});

export type LsFormfieldEvents = {
    onTextChange: EventName<CustomEvent<{ name: string; value: string }>>,
    onNumberChange: EventName<CustomEvent<{ name: string; value: number }>>,
    onBooleanChange: EventName<CustomEvent<{ name: string; value: boolean }>>
};

export const LsFormfield: StencilReactComponent<LsFormfieldElement, LsFormfieldEvents> = /*@__PURE__*/ createComponent<LsFormfieldElement, LsFormfieldEvents>({
    tagName: 'ls-formfield',
    elementClass: LsFormfieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onTextChange: 'textChange',
        onNumberChange: 'numberChange',
        onBooleanChange: 'booleanChange'
    } as LsFormfieldEvents,
    defineCustomElement: defineLsFormfield
});

export type LsHeaderBarEvents = NonNullable<unknown>;

export const LsHeaderBar: StencilReactComponent<LsHeaderBarElement, LsHeaderBarEvents> = /*@__PURE__*/ createComponent<LsHeaderBarElement, LsHeaderBarEvents>({
    tagName: 'ls-header-bar',
    elementClass: LsHeaderBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsHeaderBarEvents,
    defineCustomElement: defineLsHeaderBar
});

export type LsHelperBarEvents = NonNullable<unknown>;

export const LsHelperBar: StencilReactComponent<LsHelperBarElement, LsHelperBarEvents> = /*@__PURE__*/ createComponent<LsHelperBarElement, LsHelperBarEvents>({
    tagName: 'ls-helper-bar',
    elementClass: LsHelperBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsHelperBarEvents,
    defineCustomElement: defineLsHelperBar
});

export type LsIconEvents = NonNullable<unknown>;

export const LsIcon: StencilReactComponent<LsIconElement, LsIconEvents> = /*@__PURE__*/ createComponent<LsIconElement, LsIconEvents>({
    tagName: 'ls-icon',
    elementClass: LsIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsIconEvents,
    defineCustomElement: defineLsIcon
});

export type LsIconButtonEvents = NonNullable<unknown>;

export const LsIconButton: StencilReactComponent<LsIconButtonElement, LsIconButtonEvents> = /*@__PURE__*/ createComponent<LsIconButtonElement, LsIconButtonEvents>({
    tagName: 'ls-icon-button',
    elementClass: LsIconButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsIconButtonEvents,
    defineCustomElement: defineLsIconButton
});

export type LsIconCheckButtonEvents = NonNullable<unknown>;

export const LsIconCheckButton: StencilReactComponent<LsIconCheckButtonElement, LsIconCheckButtonEvents> = /*@__PURE__*/ createComponent<LsIconCheckButtonElement, LsIconCheckButtonEvents>({
    tagName: 'ls-icon-check-button',
    elementClass: LsIconCheckButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsIconCheckButtonEvents,
    defineCustomElement: defineLsIconCheckButton
});

export type LsInputWrapperEvents = NonNullable<unknown>;

export const LsInputWrapper: StencilReactComponent<LsInputWrapperElement, LsInputWrapperEvents> = /*@__PURE__*/ createComponent<LsInputWrapperElement, LsInputWrapperEvents>({
    tagName: 'ls-input-wrapper',
    elementClass: LsInputWrapperElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsInputWrapperEvents,
    defineCustomElement: defineLsInputWrapper
});

export type LsKeyboardShortcutsEvents = NonNullable<unknown>;

export const LsKeyboardShortcuts: StencilReactComponent<LsKeyboardShortcutsElement, LsKeyboardShortcutsEvents> = /*@__PURE__*/ createComponent<LsKeyboardShortcutsElement, LsKeyboardShortcutsEvents>({
    tagName: 'ls-keyboard-shortcuts',
    elementClass: LsKeyboardShortcutsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsKeyboardShortcutsEvents,
    defineCustomElement: defineLsKeyboardShortcuts
});

export type LsLabelEvents = NonNullable<unknown>;

export const LsLabel: StencilReactComponent<LsLabelElement, LsLabelEvents> = /*@__PURE__*/ createComponent<LsLabelElement, LsLabelEvents>({
    tagName: 'ls-label',
    elementClass: LsLabelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsLabelEvents,
    defineCustomElement: defineLsLabel
});

export type LsLeftBarEvents = {
    onManagerChange: EventName<CustomEvent<string>>,
    onClearSelected: EventName<CustomEvent<void>>
};

export const LsLeftBar: StencilReactComponent<LsLeftBarElement, LsLeftBarEvents> = /*@__PURE__*/ createComponent<LsLeftBarElement, LsLeftBarEvents>({
    tagName: 'ls-left-bar',
    elementClass: LsLeftBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onManagerChange: 'managerChange',
        onClearSelected: 'clearSelected'
    } as LsLeftBarEvents,
    defineCustomElement: defineLsLeftBar
});

export type LsListCardButtonEvents = NonNullable<unknown>;

export const LsListCardButton: StencilReactComponent<LsListCardButtonElement, LsListCardButtonEvents> = /*@__PURE__*/ createComponent<LsListCardButtonElement, LsListCardButtonEvents>({
    tagName: 'ls-list-card-button',
    elementClass: LsListCardButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsListCardButtonEvents,
    defineCustomElement: defineLsListCardButton
});

export type LsLoadingEvents = NonNullable<unknown>;

export const LsLoading: StencilReactComponent<LsLoadingElement, LsLoadingEvents> = /*@__PURE__*/ createComponent<LsLoadingElement, LsLoadingEvents>({
    tagName: 'ls-loading',
    elementClass: LsLoadingElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsLoadingEvents,
    defineCustomElement: defineLsLoading
});

export type LsLoadingIconEvents = NonNullable<unknown>;

export const LsLoadingIcon: StencilReactComponent<LsLoadingIconElement, LsLoadingIconEvents> = /*@__PURE__*/ createComponent<LsLoadingIconElement, LsLoadingIconEvents>({
    tagName: 'ls-loading-icon',
    elementClass: LsLoadingIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsLoadingIconEvents,
    defineCustomElement: defineLsLoadingIcon
});

export type LsLoadingLogoEvents = NonNullable<unknown>;

export const LsLoadingLogo: StencilReactComponent<LsLoadingLogoElement, LsLoadingLogoEvents> = /*@__PURE__*/ createComponent<LsLoadingLogoElement, LsLoadingLogoEvents>({
    tagName: 'ls-loading-logo',
    elementClass: LsLoadingLogoElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsLoadingLogoEvents,
    defineCustomElement: defineLsLoadingLogo
});

export type LsNavbarEvents = NonNullable<unknown>;

export const LsNavbar: StencilReactComponent<LsNavbarElement, LsNavbarEvents> = /*@__PURE__*/ createComponent<LsNavbarElement, LsNavbarEvents>({
    tagName: 'ls-navbar',
    elementClass: LsNavbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsNavbarEvents,
    defineCustomElement: defineLsNavbar
});

export type LsNotificationEvents = NonNullable<unknown>;

export const LsNotification: StencilReactComponent<LsNotificationElement, LsNotificationEvents> = /*@__PURE__*/ createComponent<LsNotificationElement, LsNotificationEvents>({
    tagName: 'ls-notification',
    elementClass: LsNotificationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsNotificationEvents,
    defineCustomElement: defineLsNotification
});

export type LsNumberInputEvents = { onNumberChange: EventName<CustomEvent<{ value: number }>> };

export const LsNumberInput: StencilReactComponent<LsNumberInputElement, LsNumberInputEvents> = /*@__PURE__*/ createComponent<LsNumberInputElement, LsNumberInputEvents>({
    tagName: 'ls-number-input',
    elementClass: LsNumberInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onNumberChange: 'numberChange' } as LsNumberInputEvents,
    defineCustomElement: defineLsNumberInput
});

export type LsParticipantCardEvents = {
    onMutate: EventName<LsParticipantCardCustomEvent<LSMutateEvent[]>>,
    onOpened: EventName<LsParticipantCardCustomEvent<LSApiRole>>,
    onRoleChange: EventName<CustomEvent<number>>,
    onAddParticipant: EventName<LsParticipantCardCustomEvent<{ type: LSApiRoleType; parent?: string | null; signerIndex?: number }>>
};

export const LsParticipantCard: StencilReactComponent<LsParticipantCardElement, LsParticipantCardEvents> = /*@__PURE__*/ createComponent<LsParticipantCardElement, LsParticipantCardEvents>({
    tagName: 'ls-participant-card',
    elementClass: LsParticipantCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onOpened: 'opened',
        onRoleChange: 'roleChange',
        onAddParticipant: 'addParticipant'
    } as LsParticipantCardEvents,
    defineCustomElement: defineLsParticipantCard
});

export type LsParticipantManagerEvents = {
    onMutate: EventName<LsParticipantManagerCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsParticipantManagerCustomEvent<LSMutateEvent[]>>,
    onAddParticipant: EventName<LsParticipantManagerCustomEvent<{ type: LSApiRoleType; parent?: string | null }>>
};

export const LsParticipantManager: StencilReactComponent<LsParticipantManagerElement, LsParticipantManagerEvents> = /*@__PURE__*/ createComponent<LsParticipantManagerElement, LsParticipantManagerEvents>({
    tagName: 'ls-participant-manager',
    elementClass: LsParticipantManagerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onUpdate: 'update',
        onAddParticipant: 'addParticipant'
    } as LsParticipantManagerEvents,
    defineCustomElement: defineLsParticipantManager
});

export type LsParticipantSelectEvents = {
    onRoleChange: EventName<CustomEvent<number>>,
    onAddParticipant: EventName<LsParticipantSelectCustomEvent<{ type: LSApiRoleType, parent?: string | null }>>
};

export const LsParticipantSelect: StencilReactComponent<LsParticipantSelectElement, LsParticipantSelectEvents> = /*@__PURE__*/ createComponent<LsParticipantSelectElement, LsParticipantSelectEvents>({
    tagName: 'ls-participant-select',
    elementClass: LsParticipantSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onRoleChange: 'roleChange',
        onAddParticipant: 'addParticipant'
    } as LsParticipantSelectEvents,
    defineCustomElement: defineLsParticipantSelect
});

export type LsPropsSectionEvents = NonNullable<unknown>;

export const LsPropsSection: StencilReactComponent<LsPropsSectionElement, LsPropsSectionEvents> = /*@__PURE__*/ createComponent<LsPropsSectionElement, LsPropsSectionEvents>({
    tagName: 'ls-props-section',
    elementClass: LsPropsSectionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsPropsSectionEvents,
    defineCustomElement: defineLsPropsSection
});

export type LsRadioGroupEvents = { onHandlechange: EventName<CustomEvent<string>> };

export const LsRadioGroup: StencilReactComponent<LsRadioGroupElement, LsRadioGroupEvents> = /*@__PURE__*/ createComponent<LsRadioGroupElement, LsRadioGroupEvents>({
    tagName: 'ls-radio-group',
    elementClass: LsRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onHandlechange: 'handlechange' } as LsRadioGroupEvents,
    defineCustomElement: defineLsRadioGroup
});

export type LsRadioInputEvents = NonNullable<unknown>;

export const LsRadioInput: StencilReactComponent<LsRadioInputElement, LsRadioInputEvents> = /*@__PURE__*/ createComponent<LsRadioInputElement, LsRadioInputEvents>({
    tagName: 'ls-radio-input',
    elementClass: LsRadioInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsRadioInputEvents,
    defineCustomElement: defineLsRadioInput
});

export type LsRecipientCardEvents = {
    onChangeSigner: EventName<CustomEvent<number>>,
    onFieldSelected: EventName<LsRecipientCardCustomEvent<IToolboxField>>
};

export const LsRecipientCard: StencilReactComponent<LsRecipientCardElement, LsRecipientCardEvents> = /*@__PURE__*/ createComponent<LsRecipientCardElement, LsRecipientCardEvents>({
    tagName: 'ls-recipient-card',
    elementClass: LsRecipientCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChangeSigner: 'changeSigner',
        onFieldSelected: 'fieldSelected'
    } as LsRecipientCardEvents,
    defineCustomElement: defineLsRecipientCard
});

export type LsRecipientManagerEvents = NonNullable<unknown>;

export const LsRecipientManager: StencilReactComponent<LsRecipientManagerElement, LsRecipientManagerEvents> = /*@__PURE__*/ createComponent<LsRecipientManagerElement, LsRecipientManagerEvents>({
    tagName: 'ls-recipient-manager',
    elementClass: LsRecipientManagerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsRecipientManagerEvents,
    defineCustomElement: defineLsRecipientManager
});

export type LsSelectInputEvents = { onSelectChange: EventName<CustomEvent<{ value: string }>> };

export const LsSelectInput: StencilReactComponent<LsSelectInputElement, LsSelectInputEvents> = /*@__PURE__*/ createComponent<LsSelectInputElement, LsSelectInputEvents>({
    tagName: 'ls-select-input',
    elementClass: LsSelectInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelectChange: 'selectChange' } as LsSelectInputEvents,
    defineCustomElement: defineLsSelectInput
});

export type LsStatusbarEvents = NonNullable<unknown>;

export const LsStatusbar: StencilReactComponent<LsStatusbarElement, LsStatusbarEvents> = /*@__PURE__*/ createComponent<LsStatusbarElement, LsStatusbarEvents>({
    tagName: 'ls-statusbar',
    elementClass: LsStatusbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsStatusbarEvents,
    defineCustomElement: defineLsStatusbar
});

export type LsTabsEvents = NonNullable<unknown>;

export const LsTabs: StencilReactComponent<LsTabsElement, LsTabsEvents> = /*@__PURE__*/ createComponent<LsTabsElement, LsTabsEvents>({
    tagName: 'ls-tabs',
    elementClass: LsTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsTabsEvents,
    defineCustomElement: defineLsTabs
});

export type LsTagEvents = NonNullable<unknown>;

export const LsTag: StencilReactComponent<LsTagElement, LsTagEvents> = /*@__PURE__*/ createComponent<LsTagElement, LsTagEvents>({
    tagName: 'ls-tag',
    elementClass: LsTagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsTagEvents,
    defineCustomElement: defineLsTag
});

export type LsTextEvents = NonNullable<unknown>;

export const LsText: StencilReactComponent<LsTextElement, LsTextEvents> = /*@__PURE__*/ createComponent<LsTextElement, LsTextEvents>({
    tagName: 'ls-text',
    elementClass: LsTextElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsTextEvents,
    defineCustomElement: defineLsText
});

export type LsTextInputEvents = { onTextChange: EventName<CustomEvent<{ value: string }>> };

export const LsTextInput: StencilReactComponent<LsTextInputElement, LsTextInputEvents> = /*@__PURE__*/ createComponent<LsTextInputElement, LsTextInputEvents>({
    tagName: 'ls-text-input',
    elementClass: LsTextInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onTextChange: 'textChange' } as LsTextInputEvents,
    defineCustomElement: defineLsTextInput
});

export type LsTextareaInputEvents = { onTextareaChange: EventName<CustomEvent<{ value: string }>> };

export const LsTextareaInput: StencilReactComponent<LsTextareaInputElement, LsTextareaInputEvents> = /*@__PURE__*/ createComponent<LsTextareaInputElement, LsTextareaInputEvents>({
    tagName: 'ls-textarea-input',
    elementClass: LsTextareaInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onTextareaChange: 'textareaChange' } as LsTextareaInputEvents,
    defineCustomElement: defineLsTextareaInput
});

export type LsTimelineEvents = NonNullable<unknown>;

export const LsTimeline: StencilReactComponent<LsTimelineElement, LsTimelineEvents> = /*@__PURE__*/ createComponent<LsTimelineElement, LsTimelineEvents>({
    tagName: 'ls-timeline',
    elementClass: LsTimelineElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsTimelineEvents,
    defineCustomElement: defineLsTimeline
});

export type LsTimelineStepEvents = NonNullable<unknown>;

export const LsTimelineStep: StencilReactComponent<LsTimelineStepElement, LsTimelineStepEvents> = /*@__PURE__*/ createComponent<LsTimelineStepElement, LsTimelineStepEvents>({
    tagName: 'ls-timeline-step',
    elementClass: LsTimelineStepElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsTimelineStepEvents,
    defineCustomElement: defineLsTimelineStep
});

export type LsTitleInputEvents = { onMutate: EventName<LsTitleInputCustomEvent<LSMutateEvent[]>> };

export const LsTitleInput: StencilReactComponent<LsTitleInputElement, LsTitleInputEvents> = /*@__PURE__*/ createComponent<LsTitleInputElement, LsTitleInputEvents>({
    tagName: 'ls-title-input',
    elementClass: LsTitleInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMutate: 'mutate' } as LsTitleInputEvents,
    defineCustomElement: defineLsTitleInput
});

export type LsToggleEvents = { onValueChange: EventName<CustomEvent<boolean>> };

export const LsToggle: StencilReactComponent<LsToggleElement, LsToggleEvents> = /*@__PURE__*/ createComponent<LsToggleElement, LsToggleEvents>({
    tagName: 'ls-toggle',
    elementClass: LsToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as LsToggleEvents,
    defineCustomElement: defineLsToggle
});

export type LsToolbarEvents = {
    onMutate: EventName<LsToolbarCustomEvent<LSMutateEvent[]>>,
    onUpdate: EventName<LsToolbarCustomEvent<LSMutateEvent[]>>
};

export const LsToolbar: StencilReactComponent<LsToolbarElement, LsToolbarEvents> = /*@__PURE__*/ createComponent<LsToolbarElement, LsToolbarEvents>({
    tagName: 'ls-toolbar',
    elementClass: LsToolbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMutate: 'mutate',
        onUpdate: 'update'
    } as LsToolbarEvents,
    defineCustomElement: defineLsToolbar
});

export type LsToolboxFieldEvents = {
    onFieldTypeSelected: EventName<CustomEvent<{
        label: string;
        elementType: string;
        defaultHeight: number;
        defaultWidth: number;
        formElementType: string;
        validation: number;
        fixedAspect: number | null;
    }>>
};

export const LsToolboxField: StencilReactComponent<LsToolboxFieldElement, LsToolboxFieldEvents> = /*@__PURE__*/ createComponent<LsToolboxFieldElement, LsToolboxFieldEvents>({
    tagName: 'ls-toolbox-field',
    elementClass: LsToolboxFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onFieldTypeSelected: 'fieldTypeSelected' } as LsToolboxFieldEvents,
    defineCustomElement: defineLsToolboxField
});

export type LsTooltipEvents = NonNullable<unknown>;

export const LsTooltip: StencilReactComponent<LsTooltipElement, LsTooltipEvents> = /*@__PURE__*/ createComponent<LsTooltipElement, LsTooltipEvents>({
    tagName: 'ls-tooltip',
    elementClass: LsTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsTooltipEvents,
    defineCustomElement: defineLsTooltip
});

export type LsValidationManagerEvents = NonNullable<unknown>;

export const LsValidationManager: StencilReactComponent<LsValidationManagerElement, LsValidationManagerEvents> = /*@__PURE__*/ createComponent<LsValidationManagerElement, LsValidationManagerEvents>({
    tagName: 'ls-validation-manager',
    elementClass: LsValidationManagerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LsValidationManagerEvents,
    defineCustomElement: defineLsValidationManager
});

export type LsValidationTagEvents = {
    onChangeSigner: EventName<CustomEvent<number>>,
    onSelectFieldForPlacement: EventName<CustomEvent<{ signerIndex: number; fieldType: string }>>
};

export const LsValidationTag: StencilReactComponent<LsValidationTagElement, LsValidationTagEvents> = /*@__PURE__*/ createComponent<LsValidationTagElement, LsValidationTagEvents>({
    tagName: 'ls-validation-tag',
    elementClass: LsValidationTagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onChangeSigner: 'changeSigner',
        onSelectFieldForPlacement: 'selectFieldForPlacement'
    } as LsValidationTagEvents,
    defineCustomElement: defineLsValidationTag
});

export type TestItemEvents = NonNullable<unknown>;

export const TestItem: StencilReactComponent<TestItemElement, TestItemEvents> = /*@__PURE__*/ createComponent<TestItemElement, TestItemEvents>({
    tagName: 'test-item',
    elementClass: TestItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as TestItemEvents,
    defineCustomElement: defineTestItem
});
